/**
 * Authentication tables — prefix: `auth_`
 *
 * These are typically generated by better-auth's Drizzle adapter:
 *   bunx @better-auth/cli generate
 * Configure better-auth to prefix model names with `auth_` so the whole group
 * reads together (auth_user, auth_session, auth_account, auth_verification).
 *
 * Or define them by hand, e.g.:
 *
 *   import { pgTable, text, timestamp, boolean } from "drizzle-orm/pg-core";
 *
 *   export const user = pgTable("auth_user", {
 *     id: text("id").primaryKey(),
 *     email: text("email").notNull().unique(),
 *     emailVerified: boolean("email_verified").notNull().default(false),
 *     createdAt: timestamp("created_at").notNull().defaultNow(),
 *   });
 */
export {};
